import type { CVInfo } from "~/types/cv";

export const info: CVInfo = {
  name: "Xabier Martinez",
  jobDescription: "Software Engineer",
  location: "Basque Country, Spain",
  website: "https://xmartinez.dev",
  email: "xmartinez1702@gmail.com",
  github: "https://github.com/x4b1",
  linkedin: "https://www.linkedin.com/in/xmartinez",
  about: [
    "Software engineer with a DevOps mindset and 10+ years of experience, specializing in Go programming but open to exploring other technologies. Focused on backend development, infrastructure automation, and CI/CD improvements. Passionate about the KISS principle and avoiding unnecessary reinvention.",
  ],
  languages: ["Spanish", "English", "Basque"],
  experience: [
    {
      company: "Sword Health",
      url: "https://swordhealth.com/",
      title: "Senior Software Engineer",
      startDate: "Jul 2025",
      endDate: "Present",
      description: [
        "Built AI integrations for mental health assessments and health metrics data pipelines for clinical services",
        "Developed chat service with real-time messaging, media sharing, and notifications",
        "Integrated OAuth and payment gateways to streamline clinical workflows and improve user experience",
      ],
      tags: [
        "Go",
        "PostgreSQL",
        "Node.js",
        "Vue.js",
        "GCP",
        "Helm",
        "K8S",
        "Terraform",
      ],
    },
    {
      company: "Bankable (Arex Markets)",
      url: "https://www.bnkbl.com/",
      title: "Senior Software Engineer",
      startDate: "Jul 2021",
      endDate: "Jul 2025",
      description: [
        "Built authentication service with Auth0 integration and custom authorization layer for platform-specific access control",
        "Architected customer onboarding workflows integrating AML/KYC verification, pricing engine, and eligibility services",
        "Modernized infrastructure by migrating CI/CD to GitHub Actions and managing multi-cloud deployments (AWS, GCP, Cloudflare) with Terraform",
        "Mentored engineers and automated production data anonymization for test environments",
      ],
      tags: [
        "Go",
        "PostgreSQL",
        "Node.js",
        "Vue.js",
        "AWS",
        "GCP",
        "Helm",
        "K8S",
        "Terraform",
      ],
    },
    {
      company: "Paack",
      url: "https://paack.co/",
      title: "Backend Developer",
      startDate: "Jul 2020",
      endDate: "Jul 2021",
      description: [
        "Built event-driven microservices with GraphQL APIs and gRPC using Go and Pub/Sub",
        "Integrated Twilio and Auth0, automated deployments with GitHub Actions and K8s",
      ],
      tags: ["Go", "GCP", "GraphQL", "PostgreSQL"],
    },
    {
      company: "Arex Markets",
      url: "https://www.arex.io/",
      title: "Software Developer",
      startDate: "Nov 2018",
      endDate: "Jul 2020",
      description: [
        "Built invoice automation, transaction management, and bank integrations",
        "Migrated Node.js monolith to Go microservices",
      ],
      tags: [
        "Go",
        "Node.js",
        "TypeScript",
        "Vue.js",
        "PostgreSQL",
        "Docker",
        "AWS",
        "GPC",
      ],
    },
    {
      company: "Holaluz",
      url: "https://www.holaluz.com/",
      title: "Backend Engineer",
      startDate: "Feb 2018",
      endDate: "Nov 2018",
      description: [
        "Built sales workflow tool and automated distributor onboarding",
        "Refactored legacy code and improved test coverage",
      ],
      tags: [
        "PHP",
        "Symfony",
        "Laravel",
        "Vue.js",
        "Angular",
        "PostgreSQL",
        "MySQL",
        "AWS",
      ],
    },
    {
      company: "Inbenta",
      url: "https://www.inbenta.com/en/",
      title: "Software Developer",
      startDate: "Feb 2016",
      endDate: "Feb 2018",
      description: [
        "Built content importer with web crawling and API integrations (Zendesk, Salesforce)",
        "Developed chatbot and NLP search features, customized platform for clients",
      ],
      tags: ["PHP", "Vue.js", "jQuery", "MySQL"],
    },
    {
      company: "Arin Innovation",
      url: "https://www.arin-innovation.com/en/",
      title: "Software Developer",
      startDate: "Oct 2014",
      endDate: "Feb 2016",
      description: [
        "Built Oracle JD Edwards customizations and BI reports",
      ],
      tags: [
        "Oracle",
        "Oracle JD Edwards",
        "Oracle DB",
        "PS/SQL",
        "Oracle BI publisher",
      ],
    },
  ],
  projects: [
    {
      title: "Messenger",
      description:
        "A tiny Go library to easily publish/subscribe asynchronous messages using the outbox pattern, supporting different message stores and brokers.",
      link: "https://github.com/x4b1/messenger",
    }
  ],
  education: [
    {
      title: "Computer Science Engineering",
      place: "University of the Basque Country",
      startDate: "Sep 2011",
      endDate: "Jul 2015",
    },
  ],
  labels: {
    location: "Location",
    email: "Email",
    linkedin: "Linkedin",
    github: "GitHub",
    website: "Website",
    education: "Education",
    languages: "Languages",
    workExperience: "Work Experience",
    projects: "Projects",
    moreExperienceAt: "More experience at",
    about: "About",
    personalInformation: "Personal information",
  },
  seo: {
    defaultDescription:
      "Software Engineer with 10+ years of experience specializing in Go, backend development, and DevOps. Building scalable systems and cloud infrastructure.",
    keywords:
      "Software Engineer, Go, Golang, Backend, DevOps, Infrastructure, Kubernetes, AWS, GCP, PostgreSQL, TypeScript",
    author: "Xabier Martinez",
    themeColor: "#475569",
  },
  ui: {
    downloadCV: "Download CV",
    downloadIcon: "Download",
  },
};
