import type { CVInfo } from "~/types/cv";

export const info: CVInfo = {
  name: "Xabier Martinez",
  jobDescription: "Software Engineer",
  location: "Basque Country, Spain",
  website: "https://xmartinez.dev",
  email: "xmartinez1702@gmail.com",
  github: "https://github.com/x4b1",
  linkedin: "https://www.linkedin.com/in/xmartinez",
  about: [
    "Software engineer with a DevOps mindset and 10+ years of experience, specializing in Go programming but open to exploring other technologies. Adept at backend development, infrastructure automation, and CI/CD improvements. Passionate about the KISS principle and avoiding unnecessary reinvention.",
  ],
  languages: ["Spanish", "English", "Basque"],
  experience: [
    {
      company: "Sword Health",
      url: "https://swordhealth.com/",
      title: "Senior Software Engineer",
      startDate: "Jul 2025",
      endDate: "Present",
      description: [
        "Built AI agent for mental health assessments with clinical psychology team using LangGraph and Node.js",
        "Developed data pipelines ingesting for health and other metrics.",
        "Added OAuth authentication and payment provider integrations",
      ],
      tags: [
        "Go",
        "PostgreSQL",
        "Node.js",
        "Vue.js",
        "GCP",
        "Helm",
        "K8S",
        "Terraform",
      ],
    },
    {
      company: "Bankable (Arex Markets)",
      url: "https://www.bnkbl.com/",
      title: "Senior Software Engineer",
      startDate: "Jul 2021",
      endDate: "Jul 2025",
      description: [
        "Built multi-tenant auth platform in Go with caching layer that reduced Auth0 costs",
        "Created onboarding system integrating AML/KYC providers with override support for edge cases",
        "Developed pricing engine for automated fee calculations and quotes",
        "Built company eligibility service aggregating data from multiple sources",
        "Automated prod data anonymization and replication to test environments",
        "Migrated CI/CD to GitHub Actions, standardized deployments with Helm and GitOps",
        "Managed cloud infrastructure across AWS, GCP, GitHub, and Cloudflare using Terraform",
        "Mentored engineers and worked with tech leads on platform improvements",
      ],
      tags: [
        "Go",
        "PostgreSQL",
        "Node.js",
        "Vue.js",
        "AWS",
        "GCP",
        "Helm",
        "K8S",
        "Terraform",
      ],
    },
    {
      company: "Paack",
      url: "https://paack.co/",
      title: "Backend Developer",
      startDate: "Jul 2020",
      endDate: "Jul 2021",
      description: [
        "Built Go services with GraphQL APIs and gRPC for internal communication",
        "Implemented event-driven architecture using Pub/Sub",
        "Integrated Twilio for notifications and Auth0 for authentication",
        "Set up automated deployments with GitHub Actions and K8s",
      ],
      tags: ["Go", "GCP", "GraphQL", "PostgreSQL", "RabbitMQ"],
    },
    {
      company: "Arex Markets",
      url: "https://www.arex.io/",
      title: "Software Developer",
      startDate: "Nov 2018",
      endDate: "Jul 2020",
      description: [
        "Built services for automated invoice importing and transaction management",
        "Implemented direct bank integrations for payment processing",
        "Migrated Node.js monolith to Go microservices",
      ],
      tags: [
        "Go",
        "Node.js",
        "TypeScript",
        "Vue.js",
        "PostgreSQL",
        "Docker",
        "AWS",
        "GPC",
      ],
    },
    {
      company: "Holaluz",
      url: "https://www.holaluz.com/",
      title: "Backend Engineer",
      startDate: "Feb 2018",
      endDate: "Nov 2018",
      description: [
        "Built internal tool for sales team workflows",
        "Automated distributor onboarding rejection process",
        "Refactored legacy code and added test coverage",
      ],
      tags: [
        "PHP",
        "Symfony",
        "Laravel",
        "Vue.js",
        "Angular",
        "PostgreSQL",
        "MySQL",
        "AWS",
      ],
    },
    {
      company: "Inbenta",
      url: "https://www.inbenta.com/en/",
      title: "Software Developer",
      startDate: "Feb 2016",
      endDate: "Feb 2018",
      description: [
        "Built content importer with web crawling and REST API integrations (Zendesk, Salesforce)",
        "Worked on chatbot and NLP search features with clients",
        "Customized platform for client-specific requirements",
      ],
      tags: ["PHP", "Vue.js", "jQuery", "MySQL"],
    },
    {
      company: "Arin Innovation",
      url: "https://www.arin-innovation.com/en/",
      title: "Software Developer",
      startDate: "Oct 2014",
      endDate: "Feb 2016",
      description: [
        "Gathered requirements and built Oracle JD Edwards customizations",
        "Created BI reports using Oracle BI Publisher",
        "Extended one-year contract based on performance",
      ],
      tags: [
        "Oracle",
        "Oracle JD Edwards",
        "Oracle DB",
        "PS/SQL",
        "Oracle BI publisher",
      ],
    },
  ],
  projects: [
    {
      title: "Messenger",
      description:
        "A tiny Go library to easily publish/subscribe asynchronous messages using the outbox pattern, supporting different message stores and brokers.",
      link: "https://github.com/x4b1/messenger",
    },
    {
      title: "Go Coverage Report",
      description: `A command-line tool that parses Go coverage output and generates a detailed report, supporting multiple output formats. Mainly used for publishing reports in GitHub PR checks as an alternative to third-party tools.`,
      link: "https://github.com/x4b1/go-coverage-report",
    },
  ],
  education: [
    {
      title: "Computer Science Engineering",
      place: "University of the Basque Country",
      startDate: "Sep 2011",
      endDate: "Jul 2015",
    },
  ],
  labels: {
    location: "Location",
    email: "Email",
    linkedin: "Linkedin",
    github: "GitHub",
    website: "Website",
    education: "Education",
    languages: "Languages",
    workExperience: "Work Experience",
    projects: "Projects",
    moreExperienceAt: "More experience at",
    about: "About",
    personalInformation: "Personal information",
  },
  seo: {
    defaultDescription:
      "Software Engineer with 10+ years of experience specializing in Go, backend development, and DevOps. Building scalable systems and cloud infrastructure.",
    keywords:
      "Software Engineer, Go, Golang, Backend, DevOps, Infrastructure, Kubernetes, AWS, GCP, PostgreSQL, TypeScript",
    author: "Xabier Martinez",
    themeColor: "#475569",
  },
  ui: {
    downloadCV: "Download CV",
    downloadIcon: "Download",
  },
};
